### ISSUE TITLE
checks only EN spelling

### ISSUE THREAD

**Issue by rasos** [ether/ep_spellcheck#20]
It seems i18n support does not work. 

If the language of the pad has been switched e.g. to German, German words are lined as mis-spelled and English words are correct.

![Screenshot_2021-02-14_18-54-38](https://user-images.githubusercontent.com/485723/107884583-1ba8f580-6ef6-11eb-8643-38f1633b2d6d.png)

Also the browser has set German as its first language.

**Comment by JohnMcLear** [comment]
the language detection comes from the browser, what happens if you reload the pad?

**Comment by rasos** [comment]
Mmmh, checked with a browser on another laptop, spell check and language detection is taken here correctly, browser settings are identical on both laptops, and reloaded all. Assuming it is some local issue, need further investigation, closing for now.

 Good to know that the browser language is taken, not the language which has been set for the pad.
