### ISSUE TITLE
plugin not working

### ISSUE THREAD

**Issue by latsami** [ether/ep_spellcheck#21]
Hello,
my server crashed with the fire in a data centre...
The plugin was working fine, but with the reinstall, it seems not.
It installs fine, but when I want to toggle it on in the Etherpad menu, it reloads the page and stays off.
I tried adding `ep_spellcheck: { disabledByDefault : false }` in the settings.json but it doesn't change anything (I tried putting `false` as well!). 

Here are my version numbers:
- node v10.24.0
- npm 5.8.0 
- etherpad-lite  1.8.13 

Any clue?

**Comment by JohnMcLear** [comment]
Closing as stale.
